Firebase store: Implement methods for storing and retrieving a single data point.
googleinterns/step133-2020 pull request #42
Opened 2020-07-15 02:59 UTC by MikolJiron

Implement storeDocument() and getDocument() which store and retrieve a single data point respectively.

2020-07-15 21:28 UTC, CarlosM10011 requested changes

2020-07-15 21:28 UTC, CarlosM10011 commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +      System.out.println(ServletConstantValues.NEW_DOCUMENT_ADDED +
Does App Engine log this? We may need to use a different logging API instead of this.

2020-07-15 22:48 UTC, CarlosM10011 approved these changes

2020-07-15 22:58 UTC, CarlosM10011 approved these changes

2020-07-16 20:25 UTC, Lorraine-Lyu commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +      if(document.exists()) {
space

2020-07-16 20:26 UTC, Lorraine-Lyu approved these changes

2020-07-20 14:52 UTC, hzimz approved these changes

2020-07-20 18:19 UTC, tinagrasso requested changes

2020-07-20 18:19 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +      System.out.println(ServletConstantValues.NEW_DOCUMENT_ADDED +
Use a real logger API.

2020-07-20 18:19 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +        collectionToWriteTo + ServletConstantValues.AT + future.get().getUpdateTime());
Use a string formatter.
https://screenshot.googleplex.com/ytrY40x7DWj

2020-07-20 18:19 UTC, tinagrasso commented on src/test/java/com/google/step/finscholar/firebase/FirebaseStorageManagerTest.java
> +    testObject = new TestObject(ServletConstantValues.TEST_COLLECTION_NAME, ServletConstantValues.TEST_DOCUMENT_NAME);
If these constants are only used in this file, define them here.

2020-07-20 18:19 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/data/ServletConstantValues.java
> +    public static final String EXPECTED_DOCUMENT_RETRIEVABLE = "{\"one\":\"testObjects\",\"two\":\"testDocument\"}";
Don't pollute app code with test code. Make a new file in the test directory for test constants.

2020-07-21 04:30 UTC, closed without merging