Add methods for storing and retrieving multiple data points.
googleinterns/step133-2020 pull request #55
Opened 2020-07-21 04:54 UTC by MikolJiron

2020-07-21 08:29 UTC, CarlosM10011 approved these changes

2020-07-21 18:41 UTC, tinagrasso requested changes

2020-07-21 18:41 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +        throw new FirebaseException(ServletConstantValues.UNABLE_TO_WRITE_TO_FIRESTORE + collectionToWriteTo, e);
Use string formatters.
https://screenshot.googleplex.com/ytrY40x7DWj

2020-07-22 14:16 UTC, tinagrasso approved these changes

2020-07-23 16:16 UTC, Lorraine-Lyu approved these changes

2020-07-23 16:22 UTC, hzimz approved these changes

2020-07-24 14:36 UTC, merged