Add batching code to FirebaseStorageManager to allow for infinite scroll
googleinterns/step133-2020 pull request #56
Opened 2020-07-21 05:22 UTC by MikolJiron

2020-07-21 08:26 UTC, CarlosM10011 approved these changes

2020-07-21 17:14 UTC, Lorraine-Lyu approved these changes

2020-07-21 18:43 UTC, tinagrasso requested changes

2020-07-21 18:43 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +  public static String getCollectionBatch(Firestore database, String collectionToGetFrom, int batchSizeLimit,  String lastDocID, String parameterToSortBy) throws FirebaseException {
line length

2020-07-21 18:43 UTC, tinagrasso commented on src/test/java/com/google/step/finscholar/firebase/FirebaseStorageManagerTest.java
> +      jsonWithID = FirebaseStorageManager.getCollectionBatch(firebase, TEST_COLLECTION_NAME, TEST_BATCH_SIZE_LIMIT, TEST_DOCUMENT_NAME, ServletConstantValues.DEFAULT_VALUE);
line length.

2020-07-21 18:43 UTC, tinagrasso commented on src/test/java/com/google/step/finscholar/firebase/FirebaseStorageManagerTest.java
> +    System.out.println("Batch query results with ID: " + jsonWithID);
Use a real logger.

2020-07-22 14:24 UTC, tinagrasso requested changes

2020-07-22 14:24 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +  public static String getCollectionBatch(Firestore database, String collectionToGetFrom,
No parameter validation?

2020-07-22 14:24 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +          collectionReference.orderBy(parameterToSortBy).limit(batchSizeLimit)).startAfter(document);
Can you guarantee consistency from this query?

2020-07-22 14:24 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +      String message = ServletConstantValues.DOCUMENT + lastDocID + ServletConstantValues.DNE;
String formatter :)

```
"The document with Id %s does not exist.
```

2020-07-23 16:22 UTC, hzimz approved these changes

2020-07-23 17:11 UTC, tinagrasso requested changes

2020-07-23 17:11 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +    if (lastDocID == null) {
Use Optional to protect against NPEs.
https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html

2020-07-23 17:11 UTC, tinagrasso commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +      Query page = (parameterToSortBy == null) ?
Same comment as above, use Optionals.

2020-07-24 15:43 UTC, tinagrasso requested changes
LG overall, but needs additional testing.

2020-07-24 15:43 UTC, tinagrasso commented on src/test/java/com/google/step/finscholar/firebase/FirebaseStorageManagerTest.java
> +  public void retrieveCollectionBatchWithIDandWithoutID() throws Exception {
Break this into 2 tests.

```
retrieveCollecctionBatch_withId();

retrieveCollecctionBatch_withoutId();
```

2020-07-24 15:43 UTC, tinagrasso commented on src/test/java/com/google/step/finscholar/firebase/FirebaseStorageManagerTest.java
> +  public static final int TEST_BATCH_SIZE_LIMIT = 10;
This batch size is larger than the number of test documents you have. Try to think of all the cases you need to  test to make sure you're grabbing the expected documents. I also don't see a test with no sort param set.

- first batch of collection where collection size > batch size
- middle batch of collection where collection size > batch size
- last batch of collection where # documents returns in < batch size

2020-07-24 22:44 UTC, MikolJiron commented
So I added more test to make sure the batching code functions as intended! The one with successive batches in a row was especially important to make sure it worked.

2020-07-27 13:34 UTC, Lorraine-Lyu commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
> +      throws FirebaseException {
So should I directly pass in an optional object for id, batchSize and parameterToSortBy? We need to talk about this later today.

2020-07-27 13:48 UTC, Lorraine-Lyu commented on src/main/java/com/google/step/finscholar/firebase/FirebaseStorageManager.java
>    public static String getDocument(Firestore database, String collectionToGetFrom, String documentID)
This id could be null, or an empty optional.

2020-07-27 14:14 UTC, tinagrasso approved these changes

2020-07-27 17:27 UTC, merged