Navbar template
googleinterns/step133-2020 pull request #58
Opened 2020-07-21 19:33 UTC by CarlosM10011

This pull request migrates the navbar out of the home page template. Currently, it does not touch the home page template, but it adds the files to make it work.

2020-07-21 19:47 UTC, Lorraine-Lyu approved these changes

2020-07-21 20:27 UTC, MikolJiron approved these changes

2020-07-22 14:36 UTC, tinagrasso requested changes

2020-07-22 14:36 UTC, tinagrasso commented on src/main/webapp/js/finscholar/navbar/navbar.js
> +    console.log('testing firing of handler.');
remove.

2020-07-22 14:36 UTC, tinagrasso commented on src/main/webapp/js/finscholar/navbar/navbar.js
> +    this.navbarPageIndex_ = parseInt(index, 10);
check for isNaN after parsing.

2020-07-22 16:47 UTC, CarlosM10011 commented on src/main/webapp/js/finscholar/navbar/navbar.js
> +    console.log('testing firing of handler.');
Sorry, didn't notice this comment.

2020-07-22 17:19 UTC, hzimz approved these changes

2020-07-22 17:22 UTC, tinagrasso approved these changes

2020-07-22 19:10 UTC, merged