Refactor Scholarshiplistview to use base super class
googleinterns/step133-2020 pull request #60
Opened 2020-07-21 19:51 UTC by CarlosM10011

This pr is part of a series of prs to add context tracking support to the app.

2020-07-21 19:53 UTC, Lorraine-Lyu requested changes
Are you sure you want to merge into master?

2020-07-21 19:59 UTC, CarlosM10011 commented
Sorry, didn't notice.

2020-07-21 20:01 UTC, CarlosM10011 commented
@googlebot I consent.

2020-07-21 20:13 UTC, Lorraine-Lyu approved these changes

2020-07-21 20:27 UTC, MikolJiron approved these changes

2020-07-22 00:42 UTC, tinagrasso approved these changes

2020-07-22 17:13 UTC, hzimz approved these changes

2020-07-22 17:23 UTC, tinagrasso approved these changes

2020-07-22 19:13 UTC, merged