Add factory for generating views based on navbar index
googleinterns/step133-2020 pull request #63
Opened 2020-07-21 20:18 UTC by CarlosM10011

This pr adds a factory for creating new navbar views. Will be used in the appstate manager.

2020-07-21 20:29 UTC, MikolJiron approved these changes

2020-07-21 20:33 UTC, Lorraine-Lyu approved these changes

2020-07-22 14:41 UTC, tinagrasso approved these changes

2020-07-22 17:10 UTC, hzimz requested changes

2020-07-22 17:10 UTC, hzimz commented on src/main/webapp/js/finscholar/viewfactory/viewfactory.js
> +      view = new HomePageController();
Might want to throw an error here for a value that is unexpected.

2020-07-23 21:46 UTC, hzimz approved these changes

2020-07-24 17:00 UTC, merged