Refactor scholarship page view to depend on BasicView
googleinterns/step133-2020 pull request #69
Opened 2020-07-21 21:39 UTC by CarlosM10011

This pr updates the scholarship page view to depend on the BasicView super class.

2020-07-21 21:47 UTC, hzimz approved these changes

2020-07-21 21:54 UTC, MikolJiron approved these changes

2020-07-22 20:07 UTC, Lorraine-Lyu approved these changes

2020-07-23 19:05 UTC, tinagrasso requested changes

2020-07-23 19:05 UTC, tinagrasso commented on src/main/webapp/js/finscholar/scholarshippageview/scholarshippageview.js
> +    this.fetchData_();
Not sure I understand why you need to fetch data in the constructor. Why not wait until you're ready to render?

2020-07-24 16:58 UTC, CarlosM10011 commented on src/main/webapp/js/finscholar/scholarshippageview/scholarshippageview.js
> +    this.fetchData_();
Hmm, moved it into renderView.

2020-07-24 17:19 UTC, tinagrasso approved these changes

2020-07-24 17:26 UTC, merged