Add initial implementation of an app context tracker
googleinterns/step133-2020 pull request #70
Opened 2020-07-21 21:51 UTC by CarlosM10011

This pr adds the app context class. The plan is to swap the call to the home page controller in init.js with an instance of this object.

2020-07-21 21:55 UTC, MikolJiron approved these changes

2020-07-21 21:56 UTC, Lorraine-Lyu approved these changes

2020-07-22 15:05 UTC, tinagrasso requested changes

2020-07-22 15:05 UTC, tinagrasso commented on src/main/webapp/js/finscholar/appstate/appstate.js
> +    /** @private @type {!NavBar} Initializes the code for the nav bar. */
nit: add newline.

2020-07-22 15:05 UTC, tinagrasso commented on src/main/webapp/js/finscholar/appstate/appstate.js
> +  navbarUpdate(index) {
How is this used? Are you reinstantiating the navbar every time it's clicked? Seems like it should be reusable and never change aside from some classnames.

2020-07-22 16:35 UTC, CarlosM10011 commented on src/main/webapp/js/finscholar/appstate/appstate.js
> +  navbarUpdate(index) {
Currently, rendering an entire new view recreates the whole page, so the jsaction has to bind again to the dom. Maybe I should add some helper methods to the view base class to not render the page's content...

2020-07-22 17:19 UTC, hzimz approved these changes

2020-07-22 17:36 UTC, tinagrasso approved these changes

2020-07-22 19:41 UTC, merged