Render single college query from the selected college list view item
googleinterns/step133-2020 pull request #74
Opened 2020-07-22 06:41 UTC by MikolJiron

2020-07-22 07:43 UTC, Lorraine-Lyu approved these changes

2020-07-22 16:11 UTC, Lorraine-Lyu commented on src/main/webapp/js/finscholar/singlepageview.js
> +     * @private @const {!ScholarshipDataHandler | !CollegeDataHandler} dataHandler_
I'll create a common datahandler today. You'll need to change the type to parent class later.

2020-07-24 17:34 UTC, tinagrasso requested changes

2020-07-24 17:34 UTC, tinagrasso commented on src/main/webapp/js/datahandlers/collegepagedatahandler.js
> +class CollegeDataHandler {
You probably want to wait for Lorraine's refactor and base data handler class to be merged before moving forward with this.

2020-07-24 17:34 UTC, tinagrasso commented on src/main/webapp/js/datahandlers/collegepagedatahandler.js
> +    return 200;
Future work: please make a real API call to get this number.

2020-07-24 17:34 UTC, tinagrasso commented on src/main/webapp/js/finscholar/singlepageview.js
> +     * @private @const {*} dataHandler_
Don't use * here. Lorraine create a base class for this.

2020-07-28 06:59 UTC, Lorraine-Lyu commented
@googlebot I consent.

2020-07-28 14:33 UTC, tinagrasso approved these changes
LGTM! Please make changes noted in comments.

2020-07-28 14:33 UTC, tinagrasso commented on src/main/webapp/js/datahandlers/scholarshipdatahandler.js
> +  getRequestPath_(id) {
@override?

2020-07-28 14:33 UTC, tinagrasso commented on src/main/webapp/js/datahandlers/collegepagedatahandler.js
> +  getJsonData_(json) {
Please add @override to all overridden methods.

2020-07-28 14:33 UTC, tinagrasso commented on src/main/webapp/js/datahandlers/singlepagedatahandler.js
> +   * @private
Flip @abstract and @private. The order usually goes params, return, everything else, visibility.

2020-07-28 17:33 UTC, hzimz approved these changes

2020-07-28 17:37 UTC, merged

2020-07-28 17:42 UTC, CarlosM10011 approved these changes