Fix $ formatting issue and fix anchor elements to redirect to new tab
googleinterns/step133-2020 pull request #79
Opened 2020-07-28 22:37 UTC by MikolJiron

2020-07-29 14:17 UTC, Lorraine-Lyu approved these changes

2020-07-29 15:26 UTC, tinagrasso requested changes

2020-07-29 15:26 UTC, tinagrasso commented on src/main/webapp/js/datahandlers/collegelistdatahandler.js
> +      DOLLAR_SIGN.concat(integerWithCommas(element[ANNUAL_COST])),
Make another util method to create this dollar value.

2020-07-29 17:56 UTC, tinagrasso approved these changes

2020-07-29 19:26 UTC, hzimz requested changes

2020-07-29 19:26 UTC, hzimz commented on src/main/webapp/js/datahandlers/utils.js
> +  return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
Move this regex into a constant that describes the purpose of this regex.

2020-07-30 16:55 UTC, CarlosM10011 requested changes
Can you rebase devel so we can test it for warnings?

2020-07-30 22:59 UTC, CarlosM10011 requested changes
Some linter messages:
```
src/main/webapp/js/datahandlers/collegelistdatahandler.js:22: ERROR - [JSC_EXTRA_REQUIRE_WARNING] extra require: 'ACT_SCORE' is never referenced in this file
  22| const {ACCEPTANCE_RATE, ACT_SCORE, CollegeQueryBuilder, ID, NAME} = goog.require('datahandlers.collegequerybuilder');
                              ^^^^^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:61: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  61|     return {
          ^^^^^^^^
  62|       schoolName : element[NAME],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  77|           convertToDollar(element[MEDIAN_DEBT])
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  78|     }
      ^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:85: WARNING - [JSC_UNUSED_LOCAL_ASSIGNMENT] Value assigned to local variable loadErrorPage_ is never read
  85| const loadErrorPage_ = (element, occurrence, action, error) => {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  86|   // TODO: This is being rewritten.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  87| };
      ^

src/main/webapp/js/datahandlers/collegequerybuilder.js:36: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  36| const NAME =  'school.name'
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/utils.js:31: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  31| const addSpaceToCamelCase = (str) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  32|   let result = str.replace( /([A-Z])/g, " $1" );
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  33|   return result.charAt(0).toUpperCase() + result.slice(1);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  34| }
      ^

src/main/webapp/js/datahandlers/utils.js:39: WARNING - [JSC_REDUNDANT_NULLABILITY_MODIFIER_JSDOC] string is a non-reference type which is already non-nullable.
Please remove the redundant !, which is disallowed by the style guide.
  39|  * @returns {!string} - The string representation of the number with commas.
                   ^

src/main/webapp/js/datahandlers/utils.js:41: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  41| const integerWithCommas = (num) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  42|   return num.toString().replace(NUM_REGEX, ',');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  43| }
      ^

src/main/webapp/js/datahandlers/utils.js:48: WARNING - [JSC_REDUNDANT_NULLABILITY_MODIFIER_JSDOC] string is a non-reference type which is already non-nullable.
Please remove the redundant !, which is disallowed by the style guide.
  48|  * @returns {!string} - The string representation of the number with commas and $.
                   ^

src/main/webapp/js/datahandlers/utils.js:50: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  50| const convertToDollar = (num) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  51|   return DOLLAR_SIGN.concat(integerWithCommas(num));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  52| }
      ^

src/main/webapp/js/datahandlers/utils.js:29: ERROR - [JSC_JSDOC_MISSING_TYPE_WARNING] Missing type declaration.
  29|  * @returns The formatted string.
         ^
```

2020-07-31 21:17 UTC, CarlosM10011 requested changes
Some linter messages:
```
src/main/webapp/js/datahandlers/collegelistdatahandler.js:22: ERROR - [JSC_EXTRA_REQUIRE_WARNING] extra require: 'ACT_SCORE' is never referenced in this file
  22| const {ACCEPTANCE_RATE, ACT_SCORE, CollegeQueryBuilder, ID, NAME} = goog.require('datahandlers.collegequerybuilder');
                              ^^^^^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:61: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  61|     return {
          ^^^^^^^^
  62|       schoolName : element[NAME],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  77|           convertToDollar(element[MEDIAN_DEBT])
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  78|     }
      ^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:85: WARNING - [JSC_UNUSED_LOCAL_ASSIGNMENT] Value assigned to local variable loadErrorPage_ is never read
  85| const loadErrorPage_ = (element, occurrence, action, error) => {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  86|   // TODO: This is being rewritten.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  87| };
      ^

src/main/webapp/js/datahandlers/collegequerybuilder.js:36: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  36| const NAME =  'school.name'
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/utils.js:31: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  31| const addSpaceToCamelCase = (str) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  32|   let result = str.replace( /([A-Z])/g, " $1" );
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  33|   return result.charAt(0).toUpperCase() + result.slice(1);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  34| }
      ^

src/main/webapp/js/datahandlers/utils.js:39: WARNING - [JSC_REDUNDANT_NULLABILITY_MODIFIER_JSDOC] string is a non-reference type which is already non-nullable.
Please remove the redundant !, which is disallowed by the style guide.
  39|  * @returns {!string} - The string representation of the number with commas.
                   ^

src/main/webapp/js/datahandlers/utils.js:41: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  41| const integerWithCommas = (num) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  42|   return num.toString().replace(NUM_REGEX, ',');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  43| }
      ^

src/main/webapp/js/datahandlers/utils.js:48: WARNING - [JSC_REDUNDANT_NULLABILITY_MODIFIER_JSDOC] string is a non-reference type which is already non-nullable.
Please remove the redundant !, which is disallowed by the style guide.
  48|  * @returns {!string} - The string representation of the number with commas and $.
                   ^

src/main/webapp/js/datahandlers/utils.js:50: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  50| const convertToDollar = (num) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  51|   return DOLLAR_SIGN.concat(integerWithCommas(num));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  52| }
      ^

src/main/webapp/js/datahandlers/utils.js:29: ERROR - [JSC_JSDOC_MISSING_TYPE_WARNING] Missing type declaration.
  29|  * @returns The formatted string.
         ^
```More linter messages:
```
src/main/webapp/js/datahandlers/collegepagedatahandler.js:22: WARNING - [JSC_REQUIRES_NOT_SORTED] goog.require() and goog.requireType() statements are not sorted. The correct order is:

const {ACCEPTANCE_RATE, ACT_SCORE, ANNUAL_COST, CollegeQueryBuilder, FIFTH_NET_COST, FIRST_NET_COST, FOURTH_NET_COST, MEDIAN_DEBT, NAME, SECOND_NET_COST, THIRD_NET_COST} = goog.require('datahandlers.collegequerybuilder');
const {SinglePageDataHandler} = goog.require('datahandlers.singlepagedatahandler');
const {convertToDollar} = goog.require('datahandlers.utils');

  22| const {ACCEPTANCE_RATE, ACT_SCORE, CollegeQueryBuilder, ANNUAL_COST, FIFTH_NET_COST, FIRST_NET_COST, FOURTH_NET_COST, MEDIAN_DEBT, NAME, SECOND_NET_COST, THIRD_NET_COST} = goog.require('datahandlers.collegequerybuilder');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:61: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  61|     return {
          ^^^^^^^^
  62|       schoolName : element[NAME],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  71|       cumulativeMedianDebt : convertToDollar(element[MEDIAN_DEBT])
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  72|     }
      ^^^^^
```

2020-07-31 21:52 UTC, MikolJiron commented
@CarlosM10011 I don't think you ran the linter on the latest version of college-link branch. Did you pull?

2020-07-31 22:01 UTC, MikolJiron commented
@CarlosM10011 Please pull before running the linter, it seems some of the linter messages you included in your last comment had already been resolved in one of my previous commits.

2020-08-03 14:14 UTC, CarlosM10011 approved these changes
Some linter messages:
```
src/main/webapp/js/datahandlers/collegelistdatahandler.js:22: ERROR - [JSC_EXTRA_REQUIRE_WARNING] extra require: 'ACT_SCORE' is never referenced in this file
  22| const {ACCEPTANCE_RATE, ACT_SCORE, CollegeQueryBuilder, ID, NAME} = goog.require('datahandlers.collegequerybuilder');
                              ^^^^^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:61: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  61|     return {
          ^^^^^^^^
  62|       schoolName : element[NAME],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  77|           convertToDollar(element[MEDIAN_DEBT])
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  78|     }
      ^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:85: WARNING - [JSC_UNUSED_LOCAL_ASSIGNMENT] Value assigned to local variable loadErrorPage_ is never read
  85| const loadErrorPage_ = (element, occurrence, action, error) => {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  86|   // TODO: This is being rewritten.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  87| };
      ^

src/main/webapp/js/datahandlers/collegequerybuilder.js:36: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  36| const NAME =  'school.name'
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/utils.js:31: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  31| const addSpaceToCamelCase = (str) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  32|   let result = str.replace( /([A-Z])/g, " $1" );
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  33|   return result.charAt(0).toUpperCase() + result.slice(1);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  34| }
      ^

src/main/webapp/js/datahandlers/utils.js:39: WARNING - [JSC_REDUNDANT_NULLABILITY_MODIFIER_JSDOC] string is a non-reference type which is already non-nullable.
Please remove the redundant !, which is disallowed by the style guide.
  39|  * @returns {!string} - The string representation of the number with commas.
                   ^

src/main/webapp/js/datahandlers/utils.js:41: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  41| const integerWithCommas = (num) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  42|   return num.toString().replace(NUM_REGEX, ',');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  43| }
      ^

src/main/webapp/js/datahandlers/utils.js:48: WARNING - [JSC_REDUNDANT_NULLABILITY_MODIFIER_JSDOC] string is a non-reference type which is already non-nullable.
Please remove the redundant !, which is disallowed by the style guide.
  48|  * @returns {!string} - The string representation of the number with commas and $.
                   ^

src/main/webapp/js/datahandlers/utils.js:50: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  50| const convertToDollar = (num) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  51|   return DOLLAR_SIGN.concat(integerWithCommas(num));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  52| }
      ^

src/main/webapp/js/datahandlers/utils.js:29: ERROR - [JSC_JSDOC_MISSING_TYPE_WARNING] Missing type declaration.
  29|  * @returns The formatted string.
         ^
```More linter messages:
```
src/main/webapp/js/datahandlers/collegepagedatahandler.js:22: WARNING - [JSC_REQUIRES_NOT_SORTED] goog.require() and goog.requireType() statements are not sorted. The correct order is:

const {ACCEPTANCE_RATE, ACT_SCORE, ANNUAL_COST, CollegeQueryBuilder, FIFTH_NET_COST, FIRST_NET_COST, FOURTH_NET_COST, MEDIAN_DEBT, NAME, SECOND_NET_COST, THIRD_NET_COST} = goog.require('datahandlers.collegequerybuilder');
const {SinglePageDataHandler} = goog.require('datahandlers.singlepagedatahandler');
const {convertToDollar} = goog.require('datahandlers.utils');

  22| const {ACCEPTANCE_RATE, ACT_SCORE, CollegeQueryBuilder, ANNUAL_COST, FIFTH_NET_COST, FIRST_NET_COST, FOURTH_NET_COST, MEDIAN_DEBT, NAME, SECOND_NET_COST, THIRD_NET_COST} = goog.require('datahandlers.collegequerybuilder');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/collegepagedatahandler.js:61: WARNING - [JSC_MISSING_SEMICOLON] Missing semicolon
  61|     return {
          ^^^^^^^^
  62|       schoolName : element[NAME],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  71|       cumulativeMedianDebt : convertToDollar(element[MEDIAN_DEBT])
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  72|     }
      ^^^^^
```

2020-08-03 14:15 UTC, CarlosM10011 commented
My mistake. I guess I pulled and ran against the wrong branch? They seem to be gone now :)

2020-08-03 14:19 UTC, hzimz approved these changes

2020-08-03 15:21 UTC, merged