[BUG] Add home page intro
googleinterns/step133-2020 pull request #82
Opened 2020-07-28 23:24 UTC by MikolJiron

2020-07-29 15:34 UTC, tinagrasso approved these changes

2020-07-29 15:38 UTC, CarlosM10011 requested changes

2020-07-29 15:38 UTC, CarlosM10011 commented on src/main/webapp/js/finscholar/homepagecontroller/homepagecontroller.soy
> +    <div class="mdl-card__supporting-text">
Would it break formatting if you changed these to <p> elements?

2020-07-29 19:21 UTC, CarlosM10011 approved these changes

2020-07-29 19:27 UTC, hzimz approved these changes

2020-07-30 21:32 UTC, Lorraine-Lyu approved these changes

2020-07-30 22:08 UTC, merged