Add sorting functionality to listdatahandler.
googleinterns/step133-2020 pull request #89
Opened 2020-07-30 01:04 UTC by MikolJiron

Adds a new template that contains two dropdown which are used to indicate sort parameter and direction.
Sort colleges by default. When a change is made to sort parameter or sort direction, the list is rerendered and a query is made with the new parameter changes. The only thing that needs to be changed here is scholarshiplistdatahandler in order to allow sorting of scholarships; (the backend also needs to be changed slightly: sorting by a param is already supported by the backend, but specifying sort direction is not).

2020-07-30 14:29 UTC, Lorraine-Lyu commented on src/main/webapp/js/finscholar/commonlistview/commonlistview.js
> +    this.sortBySelector.addEventListener('change', this.bindedSelectorHandler_);
Wow I'm surprised that addEventListener works here. I not sure whether it's better than jsaction, so let's first keep this here and make changes if needed later.

2020-07-30 14:30 UTC, Lorraine-Lyu approved these changes

2020-07-30 19:31 UTC, CarlosM10011 requested changes
Getting these linter messages:

```
src/main/webapp/js/datahandlers/collegelistdatahandler.js:22: ERROR - [JSC_EXTRA_REQUIRE_WARNING] extra require: 'ASCENDING' is never referenced in this file
  22| const {ACCEPTANCE_RATE, ACT_SCORE, ASCENDING, CollegeQueryBuilder, DESCENDING, ID, NAME} = 
                                         ^^^^^^^^^

src/main/webapp/js/datahandlers/collegelistdatahandler.js:22: ERROR - [JSC_EXTRA_REQUIRE_WARNING] extra require: 'DESCENDING' is never referenced in this file
  22| const {ACCEPTANCE_RATE, ACT_SCORE, ASCENDING, CollegeQueryBuilder, DESCENDING, ID, NAME} = 
                                                                         ^^^^^^^^^^

src/main/webapp/js/datahandlers/collegequerybuilder.js:89: WARNING - [JSC_MISSING_RETURN_JSDOC] Function with non-trivial return must have JSDoc indicating the return type.
  89|   static buildSortedCollectionEndpoint(batchIndex, itemsPerBatch, sortParam, sortDirection) {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  90|     return COLLEGE_LIST_ENDPT.concat(COLLEGES, AND, PRIVATE, AND, QUERY_FIELDS, 
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  95|       AND, API_KEY_FIELD, COLLEGE_API_KEY);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  96|   }
      ^^^

src/main/webapp/js/finscholar/commonlistview/commonlistview.js:19: WARNING - [JSC_REQUIRES_NOT_SORTED] goog.require() and goog.requireType() statements are not sorted. The correct order is:

const JsactionActionFlow = goog.require('jsaction.ActionFlow');
const JsactionDispatcher = goog.require('jsaction.Dispatcher');
const JsactionEventContract = goog.require('jsaction.EventContract');
const googDom = goog.require('goog.dom');
const googSoy = goog.require('goog.soy');
const {ASCENDING, DESCENDING, SORT_PARAMS_MAP} = goog.require('datahandlers.collegequerybuilder');
const {BasicView} = goog.require('basicview');
const {ListDataHandler} = goog.require('datahandlers.listdatahandler');
const {commonlistview, endoflist, listitems, loading} = goog.require('finscholar.commonlistview.templates');

  19| const JsactionActionFlow = goog.require('jsaction.ActionFlow');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/finscholar/commonlistview/commonlistview.js:86: WARNING - [JSC_MUST_HAVE_TRAILING_UNDERSCORE] Private property sortBy should end with '_'
  86|     this.sortBy = Array.from(SORT_PARAMS_MAP)[0][0];
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/finscholar/commonlistview/commonlistview.js:89: WARNING - [JSC_MUST_HAVE_TRAILING_UNDERSCORE] Private property sortOrder should end with '_'
  89|     this.sortOrder = ASCENDING;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/finscholar/commonlistview/commonlistview.js:92: WARNING - [JSC_MUST_HAVE_TRAILING_UNDERSCORE] Private property sortBySelector should end with '_'
  92|     this.sortBySelector = null;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/finscholar/commonlistview/commonlistview.js:95: WARNING - [JSC_MUST_HAVE_TRAILING_UNDERSCORE] Private property sortOrderSelector should end with '_'
  95|     this.sortOrderSelector = null;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2020-07-30 22:48 UTC, CarlosM10011 requested changes
More linter messages:

```
src/main/webapp/js/finscholar/commonlistview/commonlistview.js:19: WARNING - [JSC_REQUIRES_NOT_SORTED] goog.require() and goog.requireType() statements are not sorted. The correct order is:

const JsactionActionFlow = goog.require('jsaction.ActionFlow');
const JsactionDispatcher = goog.require('jsaction.Dispatcher');
const JsactionEventContract = goog.require('jsaction.EventContract');
const googDom = goog.require('goog.dom');
const googSoy = goog.require('goog.soy');
const {ASCENDING, DESCENDING, SORT_PARAMS_MAP} = goog.require('datahandlers.collegequerybuilder');
const {BasicView} = goog.require('basicview');
const {ListDataHandler} = goog.require('datahandlers.listdatahandler');
const {commonlistview, endoflist, listitems, loading} = goog.require('finscholar.commonlistview.templates');

  19| const JsactionActionFlow = goog.require('jsaction.ActionFlow');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2020-07-31 21:12 UTC, CarlosM10011 approved these changes

2020-08-03 14:16 UTC, tinagrasso requested changes
Can you provide a screenshot of what this looks like? I remember there being some whitespace issues between the two controls.

2020-08-03 14:16 UTC, tinagrasso commented on src/main/webapp/js/finscholar/commonlistview/commonlistview.soy
> +  <label for="sortBy">Choose Parameter to Sort By: </label>
nit: can you make this more concise? Just "Sort by" would be fine.

2020-08-03 14:16 UTC, tinagrasso commented on src/main/webapp/js/finscholar/commonlistview/commonlistview.soy
> +  <label for="sortOrder">Choose Sort Order: </label>
nit: same as above. "Order" would work just as well and unclutter the UI. Optionally a checkbox would with "Asc" as the label would do the trick.

2020-08-03 14:21 UTC, hzimz approved these changes

2020-08-03 17:37 UTC, tinagrasso approved these changes

2020-08-03 17:38 UTC, MikolJiron commented
![Screen Shot 2020-08-03 at 1 31 26 PM](https://user-images.githubusercontent.com/42727889/89210698-9465e700-d58e-11ea-8685-a52bd891491f.png)
I fixed the spacing as well.

2020-08-03 17:38 UTC, merged