All Python Code for parsing excel and storing data.
googleinterns/step133-2020 pull request #96
Opened 2020-08-03 18:28 UTC by Lorraine-Lyu

Note: This code only works on cloud shell.
This code needs python3
You may need to move it to root directory to run it.

2020-08-03 18:58 UTC, MikolJiron approved these changes
This is impressive! Awesome!

2020-08-03 19:20 UTC, tinagrasso requested changes
Add a README with instructions for running. No one will look at the comments in the PR.

2020-08-03 19:38 UTC, CarlosM10011 approved these changes

2020-08-03 20:19 UTC, tinagrasso approved these changes

2020-08-04 14:38 UTC, hzimz approved these changes

2020-08-05 17:24 UTC, merged