[BUG] Add Location to college view and fix spacing issue with scholarship
googleinterns/step133-2020 pull request #98
Opened 2020-08-04 21:16 UTC by MikolJiron

2020-08-04 21:39 UTC, Lorraine-Lyu commented on src/main/webapp/js/finscholar/collegepageview/collegepageview.js
> +  /** @private Render buttons for each scholarship related to current college. */
Thanks.

2020-08-04 21:40 UTC, Lorraine-Lyu approved these changes

2020-08-05 14:09 UTC, tinagrasso requested changes
screenshot?

2020-08-05 14:29 UTC, hzimz approved these changes

2020-08-05 14:32 UTC, CarlosM10011 approved these changes

2020-08-05 14:56 UTC, MikolJiron commented
![Screenshot 2020-08-05 at 10 54 35 AM - Display 2](https://user-images.githubusercontent.com/42727889/89428301-3fe77680-d70a-11ea-9853-43d6f0be5979.png)

2020-08-05 14:57 UTC, tinagrasso requested changes
location isn't aligned with the rest of the text.

2020-08-05 16:48 UTC, MikolJiron commented
![Screenshot 2020-08-05 at 12 46 49 PM](https://user-images.githubusercontent.com/42727889/89440625-e38c5300-d719-11ea-9aaf-3a2c568e3be9.png)
![Screenshot 2020-08-05 at 12 46 26 PM](https://user-images.githubusercontent.com/42727889/89440630-e7b87080-d719-11ea-91f1-a713f6bb8d34.png)

2020-08-05 16:48 UTC, MikolJiron commented
Fixed!

2020-08-05 17:04 UTC, tinagrasso approved these changes

2020-08-05 17:24 UTC, merged