[BUG] (list view) Changes cursor to pointer, adds highlighting, changes span to h6
googleinterns/step133-2020 pull request #99
Opened 2020-08-04 21:33 UTC by Lorraine-Lyu

2020-08-04 21:37 UTC, MikolJiron approved these changes

2020-08-05 14:12 UTC, tinagrasso requested changes
screenshot of changes?

2020-08-05 14:15 UTC, Lorraine-Lyu commented
![image](https://user-images.githubusercontent.com/39642808/89423383-0b6cbe00-d6fc-11ea-957c-c4801f974d8f.png)
The first list item has on hover effect! Sorry for no adding pictures earlier.

2020-08-05 14:25 UTC, hzimz approved these changes

2020-08-05 14:33 UTC, CarlosM10011 approved these changes

2020-08-05 15:30 UTC, Lorraine-Lyu commented
![image](https://user-images.githubusercontent.com/39642808/89432313-95ba1f80-d706-11ea-8e81-f0509de0c0e1.png)
The updated view after fixing spaces

2020-08-05 15:33 UTC, tinagrasso approved these changes

2020-08-05 15:35 UTC, merged